replicaCount: 2

service:
  type: ClusterIP

resourcesPreset: "small"

customReadinessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

customLivenessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

initContainers:
  - name: wait-for-postgres
    image: docker.io/bitnami/postgresql:latest
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - |
        until pg_isready -h pg-db-postgresql -p 5432 -U appuser; do
          echo "waiting for postgres..."
          sleep 2
        done
